## Introducción a NumPy


## ¿Qué es una librería y cómo funciona?


Una librería es un conjunto de funciones y herramientas predefinidas que permiten realizar tareas específicas sin tener que escribir el código desde cero.

En Python, las librerías se agrupan en módulos que pueden ser importados usando `import`.

Las librerías ayudan a mejorar la eficiencia y reusabilidad del código.

**Funcionamiento:**
- Las librerías se instalan y se importan en el código.
- Los desarrolladores pueden usar las funciones y clases que proporciona la librería.
- Esto evita la necesidad de implementar cada funcionalidad desde cero.

Ejemplos: NumPy, pandas, Matplotlib, entre otras.

## Cómo llamar métodos o funciones en una librería

In [15]:
# Importar la librería
import numpy as np

# Llamar a una función como np.array()
mi_array = np.array([1, 2, 3])
print(mi_array)

[1 2 3]


## ¿Qué es NumPy?


NumPy es una librería de Python utilizada para el cálculo numérico.

Proporciona soporte para arrays y matrices multidimensionales.

NumPy es la base para muchas otras librerías científicas en Python, como SciPy y pandas.

```python
# Verificar la versión de NumPy instalada
import numpy as np
print("Versión de NumPy:", np.__version__)
```

In [16]:
# Imprimir la versión de NumPy
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 1.26.4


## Importancia de NumPy


- Es extremadamente eficiente para trabajar con grandes conjuntos de datos numéricos.
- Ofrece operaciones vectorizadas, lo que acelera el cálculo y reduce la necesidad de bucles explícitos.
- Compatible con funciones matemáticas avanzadas, como álgebra lineal, transformadas de Fourier y generación de números aleatorios.
- NumPy es fundamental en áreas como análisis de datos, machine learning y simulaciones científicas.

## Creación de Arrays con NumPy

In [17]:
import numpy as np

# Crear un array a partir de una lista
array1 = np.array([1, 2, 3, 4, 5])
print("Array creado a partir de una lista:", array1)

# Crear un array lleno de ceros
array_zeros = np.zeros(5)
print("Array de ceros:", array_zeros)

# Crear un array lleno de unos
array_ones = np.ones(5)
print("Array de unos:", array_ones)

# Crear un array con un rango de valores
array_range = np.arange(0, 10, 2)
print("Array con rango de valores:", array_range)

# Crear un array con números equidistantes
array_linspace = np.linspace(0, 1, 5)
print("Array con valores equidistantes:", array_linspace)

Array creado a partir de una lista: [1 2 3 4 5]
Array de ceros: [0. 0. 0. 0. 0.]
Array de unos: [1. 1. 1. 1. 1.]
Array con rango de valores: [0 2 4 6 8]
Array con valores equidistantes: [0.   0.25 0.5  0.75 1.  ]


## Operaciones básicas con Arrays 1D

In [18]:
import numpy as np

array = np.array([1, 2, 3, 4])
print("Array original:", array)

# Operaciones matemáticas
suma = array + 2
print("Suma de 2 a cada elemento:", suma)

resta = array - 1
print("Resta de 1 a cada elemento:", resta)

multiplicacion = array * 3
print("Multiplicación por 3 de cada elemento:", multiplicacion)

division = array / 2
print("División por 2 de cada elemento:", division)

# Operaciones estadísticas
suma_total = np.sum(array)
print("Suma total de los elementos:", suma_total)

promedio = np.mean(array)
print("Promedio de los elementos:", promedio)

max_valor = np.max(array)
print("Valor máximo:", max_valor)

min_valor = np.min(array)
print("Valor mínimo:", min_valor)

Array original: [1 2 3 4]
Suma de 2 a cada elemento: [3 4 5 6]
Resta de 1 a cada elemento: [0 1 2 3]
Multiplicación por 3 de cada elemento: [ 3  6  9 12]
División por 2 de cada elemento: [0.5 1.  1.5 2. ]
Suma total de los elementos: 10
Promedio de los elementos: 2.5
Valor máximo: 4
Valor mínimo: 1


## ¿Qué es un ndarray y cómo acceder a sus elementos?


### Definición
ndarray es el tipo de array principal en NumPy y significa N-dimensional array. Es una estructura de datos que permite almacenar y operar con matrices de cualquier número de dimensiones (1D, 2D, 3D, etc.).

- Puede ser un array de una o más dimensiones.
- Soporta operaciones matemáticas eficientes.
- Todos los elementos deben ser del mismo tipo (tipado homogéneo).



In [19]:
import numpy as np

# Crear un ndarray 2D (matriz)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D (matriz):")
print(array_2d)

# Acceder al elemento en la fila 0, columna 1
elemento = array_2d[0, 1]
print("\nElemento en la fila 0, columna 1:", elemento)

# Acceder a una fila completa
fila = array_2d[1, :]
print("Fila completa (índice 1):", fila)

# Acceder a una columna completa
columna = array_2d[:, 2]
print("Columna completa (índice 2):", columna)


Array 2D (matriz):
[[1 2 3]
 [4 5 6]]

Elemento en la fila 0, columna 1: 2
Fila completa (índice 1): [4 5 6]
Columna completa (índice 2): [3 6]


## Comparación: Lista de Python vs NumPy Array


### Estructura:
- **Listas**: Pueden almacenar diferentes tipos de datos (enteros, flotantes, cadenas).
- **Arrays de NumPy**: Almacenan solo un tipo de dato (homogéneos).

### Operaciones:
- **Listas**: Las operaciones aritméticas no están vectorizadas. Necesitas bucles para operaciones sobre todos los elementos.
- **Arrays de NumPy**: Soportan operaciones vectorizadas, como suma, resta o multiplicación, aplicadas a todos los elementos sin necesidad de bucles.

In [20]:
import numpy as np

# Comparación de operaciones: Lista vs Array NumPy
lista = [1, 2, 3, 4, 5]
array = np.array([1, 2, 3, 4, 5])

# Multiplicación con listas (necesitamos un bucle)
print("Lista original:", lista)
lista_resultado = []
for elemento in lista:
    lista_resultado.append(elemento * 2)
print("Lista multiplicada por 2:", lista_resultado)

# Multiplicación con arrays (vectorizado)
print("\nArray original:", array)
array_resultado = array * 2
print("Array multiplicado por 2:", array_resultado)

Lista original: [1, 2, 3, 4, 5]
Lista multiplicada por 2: [2, 4, 6, 8, 10]

Array original: [1 2 3 4 5]
Array multiplicado por 2: [ 2  4  6  8 10]



### Velocidad y Memoria:
- **Listas**: Son más lentas cuando se manejan grandes volúmenes de datos debido a la naturaleza dinámica y heterogénea de las listas.
- **Arrays de NumPy**: Son más rápidos debido a su implementación en C y la optimización de operaciones matemáticas.
- **Listas**: Ocupan más memoria porque almacenan tipos de datos diferentes y sus referencias.
- **Arrays de NumPy**: Son más eficientes en el uso de memoria, ya que todos los elementos son del mismo tipo.`

In [31]:
import numpy as np
import time
import sys

# Creamos una lista y un array grande para comparar rendimiento
size = 1000000
print(f"Comparando rendimiento con {size} elementos:")

# Crear una lista y un array de NumPy
lista_grande = list(range(size))
array_grande = np.arange(size)

# Espacio en memoria
memoria_lista_mb = sys.getsizeof(lista_grande) / (1024 ** 2)
print(f"Espacio en memoria de la lista: {memoria_lista_mb:.6f} MB")

memoria_array_mb = array_grande.nbytes / (1024 ** 2)
print(f"Espacio en memoria del array: {memoria_array_mb:.6f} MB")

# Comparar tiempo de operaciones
start_time = time.time()
lista_resultado = [x * 2 for x in lista_grande]
lista_tiempo = time.time() - start_time
print(f"Tiempo para multiplicar lista: {lista_tiempo:.6f} segundos")

start_time = time.time()
array_resultado = array_grande * 2
array_tiempo = time.time() - start_time
print(f"Tiempo para multiplicar array: {array_tiempo:.6f} segundos")

# Prevención de división por cero
if array_tiempo > 0:
    print(f"NumPy es aproximadamente {lista_tiempo / array_tiempo:.1f} veces más rápido")
else:
    print("El tiempo para NumPy fue demasiado pequeño para ser medido con precisión.")


Comparando rendimiento con 1000000 elementos:
Espacio en memoria de la lista: 7.629448 MB
Espacio en memoria del array: 3.814697 MB
Tiempo para multiplicar lista: 0.087289 segundos
Tiempo para multiplicar array: 0.001614 segundos
NumPy es aproximadamente 54.1 veces más rápido


# Resumen de algunos métodos más importantes de NumPy

## Creación de arrays

```python
import numpy as np

# Array desde una lista
array = np.array([1, 2, 3, 4, 5])

# Arrays con valores específicos
zeros = np.zeros((3, 4))       # Array de ceros (3 filas, 4 columnas)
ones = np.ones((2, 3))         # Array de unos
full = np.full((2, 2), 7)      # Array lleno con un valor específico (7)
identity = np.eye(3)           # Matriz identidad 3x3
diagonal = np.diag([1, 2, 3])  # Matriz con valores en la diagonal

# Arrays con secuencias
range_array = np.arange(0, 10, 2)      # [0, 2, 4, 6, 8]
linear_space = np.linspace(0, 1, 5)    # 5 puntos equidistantes entre 0 y 1
log_space = np.logspace(0, 2, 5)       # 5 puntos en escala logarítmica entre 10^0 y 10^2

# Arrays aleatorios
random_uniform = np.random.rand(2, 3)             # Valores entre 0 y 1 (distribución uniforme)
random_normal = np.random.randn(2, 3)             # Distribución normal (media 0, desviación 1)
random_int = np.random.randint(0, 10, (3, 3))     # Enteros aleatorios entre 0 y 9
```

## Propiedades de arrays

```python
a = np.array([[1, 2, 3], [4, 5, 6]])

a.shape      # Dimensiones (2, 3)
a.ndim       # Número de dimensiones (2)
a.size       # Número total de elementos (6)
a.dtype      # Tipo de datos (int64, float64, etc.)
a.itemsize   # Tamaño en bytes de cada elemento
```

## Operaciones básicas

```python
# Operaciones aritméticas
a + 2        # Suma escalar a cada elemento
a * 3        # Multiplicación por escalar
a + b        # Suma elemento a elemento entre arrays
a * b        # Multiplicación elemento a elemento

# Operaciones matriciales
np.dot(a, b)     # Producto matricial
a @ b            # Producto matricial (sintaxis Python 3.5+)
np.matmul(a, b)  # Producto matricial

# Operaciones de comparación
a > 2        # Devuelve array booleano
np.equal(a, b)   # Compara elemento a elemento
```

## Indexación y modificación

```python
# Acceso a elementos
a[0, 1]      # Elemento en la fila 0, columna 1
a[0, :]      # Primera fila completa
a[:, 1]      # Segunda columna completa
a[0:2, 1:3]  # Submatriz (filas 0-1, columnas 1-2)

# Modificar elementos
a[0, 0] = 10         # Cambiar un elemento
a[:, 0] = [10, 20]   # Cambiar una columna completa
```

## Manipulación de forma

```python
a = np.arange(12)

a.reshape(3, 4)      # Cambia la forma a una matriz 3x4
a.reshape(3, -1)     # -1 significa "calcular automáticamente"
a.flatten()          # Convierte en array 1D
a.ravel()            # Similar a flatten, pero puede devolver una vista

# Agregar/eliminar ejes
np.expand_dims(a, axis=0)    # Añade un nuevo eje
np.squeeze(a)                # Elimina ejes de dimensión 1

# Concatenación y división
np.concatenate([a, b], axis=0)   # Une arrays a lo largo de un eje
np.vstack([a, b])                # Apila verticalmente 
np.hstack([a, b])                # Apila horizontalmente
np.split(a, 3)                   # Divide en 3 partes iguales
```

## Operaciones estadísticas

```python
np.min(a)        # Valor mínimo
np.max(a)        # Valor máximo
np.mean(a)       # Media aritmética
np.median(a)     # Mediana
np.std(a)        # Desviación estándar
np.var(a)        # Varianza
np.sum(a)        # Suma de todos los elementos
np.sum(a, axis=0)  # Suma a lo largo del eje 0 (por columna)
np.cumsum(a)     # Suma acumulativa
np.percentile(a, 75)  # Percentil 75
```

## Álgebra lineal (np.linalg)

```python
np.linalg.inv(a)         # Matriz inversa
np.linalg.det(a)         # Determinante
np.linalg.eig(a)         # Autovalores y autovectores
np.linalg.svd(a)         # Descomposición en valores singulares
np.linalg.norm(a)        # Norma euclidiana
np.linalg.solve(a, b)    # Resolver sistema de ecuaciones lineales Ax = b
```

## Funciones matemáticas

```python
np.abs(a)        # Valor absoluto
np.sqrt(a)       # Raíz cuadrada
np.exp(a)        # Exponencial (e^x)
np.log(a)        # Logaritmo natural
np.log10(a)      # Logaritmo base 10
np.sin(a)        # Seno
np.cos(a)        # Coseno
np.tan(a)        # Tangente
np.round(a, 2)   # Redondeo a 2 decimales
np.floor(a)      # Redondeo hacia abajo
np.ceil(a)       # Redondeo hacia arriba
```

## Broadcasting

```python
# Broadcasting permite operar arrays de diferentes formas
a = np.array([[1, 2, 3], [4, 5, 6]])   # Forma (2, 3)
b = np.array([10, 20, 30])             # Forma (3,)

# NumPy hace broadcasting automáticamente
c = a + b     # b es "expandido" para coincidir con la forma de a
```

## Máscaras booleanas

```python
# Filtrado de elementos
mask = a > 2                  # Crea array booleano
filtered = a[mask]            # Selecciona solo elementos donde mask es True
filtered = a[a > 2]           # Forma compacta

# Reemplazo condicional
a[a < 0] = 0                  # Reemplaza valores negativos con cero

# Funciones with where
np.where(a > 2, a, 0)         # Mantiene valores >2, reemplaza otros con 0
```

## Operaciones de conjunto

```python
np.unique(a)                  # Valores únicos
np.intersect1d(a, b)          # Intersección de dos arrays
np.union1d(a, b)              # Unión
np.setdiff1d(a, b)            # Diferencia (elementos en a pero no en b)
np.in1d(a, b)                 # Comprueba si elementos de a están en b
```

## Guardar y cargar arrays

```python
# Guardar
np.save('array.npy', a)                     # Formato binario de NumPy
np.savez('arrays.npz', x=a, y=b)            # Múltiples arrays en un archivo
np.savetxt('array.csv', a, delimiter=',')   # Formato texto

# Cargar
loaded_array = np.load('array.npy')
arrays = np.load('arrays.npz')              # Devuelve objeto tipo diccionario
from_text = np.loadtxt('array.csv', delimiter=',')
```